### ISSUE TITLE
pubsub: add conformance tests for concurrent calls to ReceiveBatch and SendAcks

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#856] opened 2018-11-30 22:06 UTC
The concrete API doesn't yet make concurrent use of ReceiveBatch, but we want to make sure drivers can handle it in case we later make use of it in the concrete API.

**Comment by jba** [comment] 2018-11-30 22:51
Same for SendAcks.

One alternative is to have drivers provide their preferred value for `maxHandlers`.

**Comment by vangent** [comment] 2019-02-14 17:51
Dupe of #965

**Closed by vangent** 2019-02-14 17:51 UTC
