### ISSUE TITLE
docs: go-cloud  API design considerations

### ISSUE THREAD

**Issue by bklau** [google/go-cloud#251] opened 2018-07-27 15:22 UTC
I don't see any high-level API design for go-cloud.
There are a number of issues that need addressing for this project  to become useful.  
1)  Common API  spec for Cloud Providers to support 
2) API Extension Points for implementing Cloud Provider-specific features 
3)  How to register and use Third Party pluggables . I assume that someone could write better pluggable with richer features.
4) API Conformance level. (Take ODB/JDBC Drivers specs  as lessons
See https://github.com/cncf/k8s-conformance/blob/master/README-WG.md as example also)

**Comment by zombiezen** [comment] 2018-08-03 17:01
We have a [internal/docs/design.md](https://github.com/google/go-cloud/blob/master/internal/docs/design.md) file that describes some of the high-level design decisions, but it's not in an easily consumable format yet.

Go Cloud by design does not require registration: each generic type takes in an interface that documents the expectations of the API (see [`driver.Bucket`](https://godoc.org/github.com/google/go-cloud/blob/driver#Bucket) docs, for instance). It is expected that if applications need cloud provider specific functionality that they use their cloud provider's SDK.

We don't have a sense of conformance level at the moment, since either a type implements an interface or it doesn't. We expect that as the interfaces evolve, some implementations may not implement all interfaces and the generic type will handle surfacing that to the user of the type.

**Comment by vangent** [comment] 2018-09-21 21:21
Closing this.

> Common API spec for Cloud Providers to support

[driver.Driver](https://github.com/google/go-cloud/blob/master/blob/driver/driver.go) provides a interface(s) for a provider to implement for each portable API (I linked to the one for **blob**).

> API Extension Points for implementing Cloud Provider-specific features

See PR #471, which is adding a section to [design.md](https://github.com/google/go-cloud/blob/master/internal/docs/design.md) about "escape hatches", which addresses this need. #470 tracks the implementation. Feedback is welcome on that issue or on the mailing list.

> How to register and use Third Party pluggables.

I am not sure what this means, but I think "escape hatches" should address this as well.

> API Conformance level. 

Thanks for the links. We've implemented [conformance tests](https://github.com/google/go-cloud/blob/master/blob/drivertest/drivertest.go) for each API.

**Closed by vangent** 2018-09-21 21:21 UTC
