### ISSUE TITLE
Add listing of objects in a bucket based on some prefix

### ISSUE THREAD

**Issue by danielblazevski** [google/go-cloud#397] opened 2018-09-05 20:38 UTC
First of all, this is a super interesting project that is much needed in cloud infrastructure. 

I think it would be neat to be able to add the ability to do get a list of all objects in a buck based on some prefix.  For instance, I often find myself doing stuff like 
```
gsutil ls gs://my_bucket/my_prefix/*
```
whether using the command line or in code.  

Happy to discuss further on a scope for this functionality.

**Comment by vangent** [comment] 2018-09-05 23:10
Hi Daniel, thanks for checking out Go Cloud!

I think this issue is a dupe of #241.

**Closed by vangent** 2018-09-05 23:10 UTC
Labels: duplicate
