### ISSUE TITLE
blob/azureblob: Non-existent storage containers don't error until timeout after 60s, and error code is "Unknown"

### ISSUE THREAD

**Issue by bensussman** [google/go-cloud#2893] opened 2020-11-20 18:47 UTC
### Describe the bug

When listing the contents of azure bucket that does not exist, the error returned does NOT have a valid "error code" (so there is no way to easily identify it as a "bucket does not exist error") and it takes 60s for the error to be returned (because it's a timeout).

Please see https://github.com/google/go-cloud/issues/2892 for more context

### To Reproduce

Run this following code:

```
func main() {
	ctx := context.Background()
	storageAccountName := "totallyfakestorageaccountname"
	containerName := "totallyfakeblobcontainername"
	exists, err := isPublic(ctx, storageAccountName, containerName)
	if err != nil {
		fmt.Println("ERROR:", err)
	}
	fmt.Println("storageAccountName:", storageAccountName, "containerName:", containerName, "Exists?", exists, "err?", err != nil
}

func isPublic(ctx context.Context, storageAccountName, containerName string) (bool, error) {
	accountName := azureblob.AccountName(storageAccountName)
	anonCreds := azblob.NewAnonymousCredential()
	pipeline := azureblob.NewPipeline(anonCreds, azblob.PipelineOptions{})

	bucket, err := azureblob.OpenBucket(ctx, pipeline, accountName, containerName, &azureblob.Options{})
	if err != nil {
		return false, err
	}

	iter := bucket.List(&blob.ListOptions{Delimiter: "/"})
	_, err = iter.Next(ctx)
	if err != nil && err != io.EOF {
		return false, err
	}
	return true, nil
}
```

## Expected behavior

I expect it to fail immediately instead of after 60s, and I expect the returned error to have a nice `code` which tells the caller that it was a "bucket does not exist / is not accessible" error.

Instead, the output is:

```
ERROR: blob (code=Unknown): -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /Users/ben/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/error.go:154
HTTP request failed

Get "https://totallyfakestorageaccountname.blob.core.windows.net/totallyfakeblobcontainername?comp=list&delimiter=%2F&maxresults=1000&restype=container&timeout=61": dial tcp: lookup totallyfakestorageaccountname.blob.core.windows.net: no such host

storageAccountName: totallyfakestorageaccountname containerName: totallyfakeblobcontainername Exists? false err? true
```

### Version

`gocloud.dev v0.20.0`

### Additional context

Please see https://github.com/google/go-cloud/issues/2712 and https://github.com/google/go-cloud/issues/2892 for additional context.

**Comment by vangent** [comment] 2020-11-20 19:17
I'm not sure we can fix this. It should work if you have a real storage account, but use an invalid container/bucket (I am adding tests for this as part of #2892). But using an invalid storage account name (or possibly the anonymous creds?) results in HTTP requests to an invalid host (`totallyfakestorageaccountname.blob.core.windows.net`), and it looks like the Azure libraries timeout on that.

**Comment by vangent** [comment] 2020-11-20 19:29
I have verified that using a real pipeline but an invalid account name returns a "502" error right away, which results in an "Unknown" error code. I think this is fine (I am wary of treating all 502s as "Not Found").

I can reproduce your problem with the code above, but I'm not sure what to do about it, since the delay/timeout is all on the first call we make to Azure.

**Comment by bensussman** [comment] 2020-11-20 21:34
What do you mean by "a real pipeline" @vangent? Is that opposed to an "anonymous" client? Or do you mean using a valid `Storage Account Name` with an invalid `Blob Container Name` (yes, these azure names are confusing, but 🤷‍♂️ )?

We handle "public" buckets differently than "private" ones, so we validate that a bucket is public using the code above, is there a better way to do this which gets around the 60s timeout?

**Comment by vangent** [comment] 2020-11-20 21:45
I have tried 3 things:
1. Your code above. It does as you describe (60s delay then fails with `502`).
2. The regular test we have, which creates a pipeline with creds. 
  * With an invalid `Storage Account Name`, it fails right away with a `502` (due to host not found).
  * With a valid `Storage Account Name` but an invalid `Blob Container Name`, it fails right away with `NotFound`.

The most obvious difference between #1 and #2a is the anonymous pipeline vs one with creds, but there may be other differences.

Given that everything works until we try to call Azure, and the first call takes 60 seconds before returning the error, I'm just not sure how to handle this better. But, I am not an Azure expert.

**Comment by vangent** [comment] 2020-11-20 21:46
This is the first RPC we make:
https://github.com/google/go-cloud/blob/master/blob/azureblob/azureblob.go#L677

**Comment by bensussman** [comment] 2020-11-20 22:37
Understood. I still have a problem of "how do i detect if a bucket is public or not"?

For example, here is a public dataset hosted on azure: https://azure.microsoft.com/en-us/services/open-datasets/catalog/tartanair-airsim-simultaneous-localization-and-mapping/

If I want to test "is this accessible from my current context?" I can use the code above to accurately test if it's public and viola: it correctly returns "yes it's accessible with the anonymous credentials, and therefore public!"

However, that same solution does NOT work for non-existent storage account names as previously discussed, so instead if can provide credentials, including a bogus account key (i do not have access to an account key for this public bucket) i get the following error:

```
$ go run main.go
ERROR: blob (code=Unknown): -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /Users/ben/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.9.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:da980ef9-a01e-001a-6c8c-bf8748000000
Time:2020-11-20T22:32:13.8656434Z, Details:
   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'kp5dgt8ACwqNcQ2fJd7k8xFmaWXFK4US8JU3qi7Zc2M=' is not the same as any computed signature. Server used following string to sign: 'GET

x-ms-client-request-id:c622b120-0db6-4154-7568-293e146d71d7
x-ms-date:Fri, 20 Nov 2020 22:32:13 GMT
x-ms-version:2018-11-09
/tartanair/tartanair-release1
comp:list
delimiter:/
maxresults:1000
restype:container
timeout:61'.
   Code: AuthenticationFailed
   GET https://tartanair.blob.core.windows.net/tartanair-release1?comp=list&delimiter=%2F&maxresults=1000&restype=container&timeout=61
   Authorization: REDACTED
   User-Agent: [go-cloud/blob/0.1.0 Azure-Storage/0.9 (go1.15.2; darwin)]
   X-Ms-Client-Request-Id: [c622b120-0db6-4154-7568-293e146d71d7]
   X-Ms-Date: [Fri, 20 Nov 2020 22:32:13 GMT]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Content-Length: [785]
   Content-Type: [application/xml]
   Date: [Fri, 20 Nov 2020 22:32:13 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [da980ef9-a01e-001a-6c8c-bf8748000000]

storageAccountName: tartanair containerName: tartanair-release1 Exists? false err? true
```

Given this, i have no way to evaluate the "public-ness" of a given "Storage Acct Name + Blob Container Name" pair without waiting the 60s? I'd like to believe there's a better solution!!

**Comment by bensussman** [comment] 2020-11-20 22:44
@vangent I am not able to reproduce 2A locally. Here is my test code:

```
func main() {
	ctx := context.Background()
	storageAccountName := "totallymadeupstorageaccountname"
	containerName := "totallymadeupcontainername"
	exists, err := isPublic(ctx, storageAccountName, containerName)
	if err != nil {
		fmt.Println("ERROR:", err)
	}
	fmt.Println("storageAccountName:", storageAccountName, "containerName:", containerName, "Exists?", exists, "err?", err != nil)
}

func isPublic(ctx context.Context, storageAccountName, containerName string) (bool, error) {
	accountName := azureblob.AccountName(storageAccountName)
	accountKey := azureblob.AccountKey("tZa8yKquZlLy+C0poNI+uZhZP7/dxVvMzEvPvyPdnybbUgGlQuqCZ3HCrtDAQ+7LujDZAx/eFEvGZS0DkvpIww==")
	credential, err := azureblob.NewCredential(accountName, accountKey)
	if err != nil {
		return false, err
	}
	pipeline := azureblob.NewPipeline(credential, azblob.PipelineOptions{})

	bucket, err := azureblob.OpenBucket(ctx, pipeline, accountName, containerName, &azureblob.Options{})
	if err != nil {
		return false, err
	}

	iter := bucket.List(&blob.ListOptions{Delimiter: "/"})
	_, err = iter.Next(ctx)
	if err != nil && err != io.EOF {
		return false, err
	}
	return true, nil
}
```

Note that account key is a valid one for a public bucket that I made in my personal Azure account.

**Comment by vangent** [comment] 2020-11-20 23:52
I can reproduce your first test, and I believe you about the second one; there must be some other difference it what I tried and your code.

However, this still doesn't help with a solution for the problem you're describing. We're making an RPC (well, HTTP request) to Azure that should fail with some kind of authentication or resource-not-found error, and instead it hangs for 60 seconds and then returns a generic `502`. This seems like a bug with Azure to me.

BTW, I merged the `bucket.IsAccessible` PR so your tests should be simpler now.

If you can find a better way to deal with this, PRs are welcome. You could also try filing a bug upstream with Azure. If the call we make returned a reasonable error quickly it would probably just work, or it would be an easy fix to check for the error.

**Comment by vangent** [comment] 2020-11-21 00:21
If you create your Pipeline with `PipelineOptions` like this: `azblob.PipelineOptions{Retry:azblob.RetryOptions{MaxTries:1}}` then it fails right away. It looks like `Pipeline` by default retries for up to a minute.

Can you try patching in the changes in https://github.com/google/go-cloud/pull/2896 and see if that helps? I think it should make the error codes better (and in particular, `bucket.IsAccessible` might work for invalid storage account name.

It doesn't solve the "it takes 60 seconds" problem, I think you need to change the PipelineOptions as described above for that.

**Closed** 2020-11-30 17:49 UTC

**Comment by bensussman** [comment] 2020-12-02 22:02
Thanks @vangent, adding `azblob.PipelineOptions{Retry:azblob.RetryOptions{MaxTries:1}}` fixes the 60 second delay to fail!

I noticed that  #2896  no longer includes a method to see "does this bucket even exist". Is the best strategy for that still 

```
func canAccessBucket(ctx context.Context, bucket *blob.Bucket) bool {
	iter := bucket.List(&blob.ListOptions{Delimiter: "/"})
	_, err := iter.Next(ctx)
	if err != nil && !errors.Is(err, io.EOF) {
		return false
	}
	return true
}
```

Or is there an easier / simpler method given the added error codes?

Finally, when i try `go get gocloud.dev@master` in my project, it updates a lot of adjacent dependencies (aws and azure sdks for example, but notably *not* `github.com/docker/docker`) and then proceeds to break with:

```
# github.com/docker/docker/pkg/term
../../../go/pkg/mod/github.com/docker/docker@v17.12.0-ce-rc1.0.20200309214505-aa6a9891b09c+incompatible/pkg/term/tc.go:13:28: undefined: unix.SYS_IOCTL
../../../go/pkg/mod/github.com/docker/docker@v17.12.0-ce-rc1.0.20200309214505-aa6a9891b09c+incompatible/pkg/term/tc.go:18:28: undefined: unix.SYS_IOCTL
../../../go/pkg/mod/github.com/docker/docker@v17.12.0-ce-rc1.0.20200309214505-aa6a9891b09c+incompatible/pkg/term/termios_bsd.go:24:31: undefined: unix.SYS_IOCTL
../../../go/pkg/mod/github.com/docker/docker@v17.12.0-ce-rc1.0.20200309214505-aa6a9891b09c+incompatible/pkg/term/termios_bsd.go:37:31: undefined: unix.SYS_IOCTL
```

I see it was an issue here: https://github.com/moby/term/issues/15 but not in github.com/moby/moby... I'll create an issue in `moby/moby`, but currently this is a blocker for me testing out the updates to `gocloud.dev` 😢
