### ISSUE TITLE
pubsub: support opening Topics and Subscriptions from URLs

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#1027] opened 2018-12-21 05:18 UTC
It is [possible](https://godoc.org/gocloud.dev/blob#Open) to construct a `blob.Blob` from a URL, and it would be useful to be able to do the same for pubsub Topics and Subscriptions, something like this:
```
import (
        "gocloud.dev/pubsub"
)

func openTopics() {
        ctx := context.Background()
        gcpTopic := pubsub.OpenTopic(ctx, "https://pubsub.googleapis.com/v1/projects/myproject/topics/mytopic", nil)
        awsTopic := pubsub.OpenTopic(ctx, "arn:aws:sns:us-east-2:221420415498:test-topic", nil)
        // ...
}
```

**Comment by jba** [comment] 2018-12-21 12:16
Not in favor. It seems like a cute convenience feature more than something actually useful.

**Comment by ijt** [comment] 2018-12-21 18:31
URLs aren't only for things that can be served over HTTP. They're Universal Resource Locators, not Protocol-Specific Resource Locators.

I'm still in favor of adding this, but if we decide not to then we should also remove it from `blob`.

**Comment by vangent** [comment] 2018-12-21 19:53
Per discussion, we're going to do this but put the code in the sample pubsub app instead of in the `pubsub` package. If there's demand it will be easy to move it.

**Comment by jba** [comment] 2018-12-21 19:57
Just to document what I see as the key point (due to Robert): 

There are two kinds of programs. The first uses one cloud provider at a time—it may start with AWS, then switch to GCP. Or maybe there are two versions of the binary. For these programs, using `wire` or hand-writing code to make resources is fine.

The second kind of program wants to let users pick their provider dynamically from a large set. For example, Hugo wants to let users configure a bucket, and wants them to be able to choose from any provider. URLs make sense for this case.

**Comment by ijt** [comment] 2019-01-09 02:11
To that list I would add a third kind of program that uses multiple clouds for various purposes.

**Comment by ijt** [comment] 2019-01-25 01:45
I think I'm persuaded by Ross's objections about the global mutable state that would be needed to make the URL-based Open* functions I had in mind. I'm currently looking for ways to make it easier for app developers to use Wire to work with topics and subscriptions.

**Comment by ijt** [comment] 2019-02-11 23:07
It looks like the tide has turned and we're doing URLs.

@zombiezen are we at a point where it makes sense to use your design to add this for pubsub?

**Comment by vangent** [comment] 2019-02-11 23:22
Yes, but I've asked @shantuo to do this (for `secrets`, `runtimevar`, `pubsub`), once @zombiezen 's blob PR (#1282) is in. Assigning to him... (I already assigned #1174, didn't realize that there was a pubsub-specific issue).

**Comment by vangent** [comment] 2019-02-27 19:42
Dupe of #1174.

**Closed by vangent** 2019-02-27 19:42 UTC
