### ISSUE TITLE
gocloud.dev/mysql/gcpmysql: gcp mySQL options are not being handle in Open

### ISSUE THREAD

**Issue by g8rswimmer** [google/go-cloud#2745] opened 2020-02-14 20:59 UTC
#1348 # Describe the bug

When calling the `mysql.Open` with the DNS string including options.  The database connection is opened without any of the options applied.

### To Reproduce

```go
db, err := mysql.Open(ctx,
		"gcpmysql://user:password@example-project/region/my-instance01/testdb?parseTime=true")
```
After this line of code successfully completes, the database connection will be opened.  However, the `parseTime` option will not have been applied.

## Expected behavior

When the `mysql.Open` connection string is passed, all of the options will be applied to the database connection.

### Version

gocloud.dev v0.19.0

### Additional context

After some investigating, I think that the problem could be in the use of the `go-sql-driver/mysql` configuration structure.  When calling `FormatDSN` method, it looks like the options are taken from the configuration structure members and not the string.

**Comment by vangent** [comment] 2020-03-14 16:55
Could you send a PR and test for this?

**Comment by g8rswimmer** [comment] 2020-03-16 22:16
@vangent Sure, I will get something up and add you as a reviewer (or anyone else that would need to approve)

**Comment by g8rswimmer** [comment] 2020-03-17 23:39
@vangent 
I have a branch for PR, but I do not have write access to push a branch.

**Comment by vangent** [comment] 2020-03-18 00:06
Hi @g8rswimmer -- you will need to create a fork and then a branch in your fork:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

Also see https://github.com/google/go-cloud/blob/master/CONTRIBUTING.md#making-a-pull-request.

**Comment by g8rswimmer** [comment] 2020-06-23 03:36
@vangent Should I close this as the new version addresses the issue?  I have tested on multiple mySQL gcp instances.

**Comment by vangent** [comment] 2020-06-23 16:19
Sure, if the issue is fixed let's close it.

**Closed by vangent** 2020-06-23 16:19 UTC
