### ISSUE TITLE
all: use public import path gocloud.dev

### ISSUE THREAD

**Issue by vsekhar** [google/go-cloud#77] opened 2018-06-06 20:40 UTC

**Comment by jba** [comment] 2018-11-29 22:35
We have the domain `gocloud.dev`. We want it to start our vanity import paths. E.g.  `gocloud.dev/blob`.

After some discussion, Ross and I came up with the following implementation plan. It's based on similar work he's done for `gg`. We'll statically host the pages we need on the Github Pages site that corresponds to this repo (`github.io/google/go-cloud`).

- [ ] Point the domain to the GH Pages domain.
- [ ] Configure GH Pages to accept SSL traffic from `gocloud.dev`.
- [ ] Create the pages with the meta tags using [hugo](https://github.com/gohugoio/hugo).
- [ ] Push the pages to this repo.
- [ ] Automate this process.

Regarding the last step: Ross has configured Travis to [re-create the site on green](https://github.com/zombiezen/gg/blob/master/.travis.yml#L26-L41). We'll adopt that idea.

**Comment by jba** [comment] 2018-11-29 22:50
@vangent for thoughts/approval.

**Comment by vangent** [comment] 2018-11-29 22:56
SGTM. Thanks!

**Comment by zombiezen** [comment] 2018-11-30 16:53
What's our migration plan for preserving existing users using `github.com/google/go-cloud`? It would be nice to give a grace period.

**Comment by jba** [comment] 2018-11-30 17:52
I'm not sure how it works with modules, but with ordinary packages we can just leave off the import comment.

**Comment by zombiezen** [comment] 2018-11-30 18:16
That wouldn't allow gradual migration: both import paths would look like they have full versions of the types. It would be best to set up `github.com/google/go-cloud` to "forward" (a la [golang.org/cl/137076](https://golang.org/cl/137076)) to the corresponding `gocloud.dev/...` packages.

It may end up being the case that this is impractical, but I'd like us to be in the habit of designing not to break folks where possible.

**Comment by zombiezen** [comment] 2018-11-30 21:10
`gocloud.dev`. The problem is that if we leave off import comments, then folks can import full types from either. Concretely, you could import two distinct types: `*gocloud.dev/blob.Bucket` and `*github.com/google/go-cloud.Bucket`.

I assert that the best case here would be that `*github.com/google/go-cloud.Bucket` becomes a type alias of `*gocloud.dev/blob.Bucket`. The next best thing would be for things to break loudly if imported as `github.com/google/go-cloud` (so add the import comment). I think the worst would be not adding the import comment, since then if package A uses `*github.com/google/go-cloud.Bucket` and package B uses `*gocloud.dev/blob.Bucket`, they confusingly cannot interoperate because the types are distinct.

**Comment by jba** [comment] 2018-12-08 20:19
After discussion, we determined that it was infeasible to make this change in a non-breaking way. So we are going to introduce the new import paths and stop the old ones from working as atomically as possible.

The detailed plan is as follows: First, we'll email the go-cloud list saying we're planning to do the change in (say) 48 hours, or whatever we decide. Then, at the designated time, we'll do the following as quickly as possible:

1. Run the `internal/imports/makeimport.sh` script to generate the redirect files, and manually add them to the `gh-pages` branch. (Later, we'll automate this with travis.) After this step, both import paths will be available.

1. Create a PR that:
   1. Changes module paths
   2. Changes import paths
   3. Adds import path comments 
   
   Get the PR approved but do not submit it. (Tests will not pass, because the module proxy used by Travis is not configured correctly.)

1. Rebuild the module cache for the proxy, by following the [instructions](https://github.com/google/go-cloud/blob/master/internal/proxy/README.md) in the local branch of the PR.

1. Re-run the tests on the PR through Travis.

1. Submit the PR.

**Comment by zombiezen** [comment] 2018-12-10 15:04
SGTM. One thing I don't quite understand: why do we need to rebuild the module cache? Seems like it would still work regardless of what path Go Cloud is on, since it just has the dependencies stored in it, not Go Cloud itself.

**Comment by jba** [comment] 2018-12-10 22:58
I thought I noticed the Go Cloud module zip in there. I think one of the submodules needs it.

**Comment by zombiezen** [comment] 2018-12-10 23:02
Got it. Thanks! Perhaps we should release one version of Go Cloud on the old import path first, since there is the Wire quasi-breaking change still going through (0.6 -> 0.7). That way, we can then immediately cut a new release as 0.8 with no other changes. WDYT?

**Comment by jba** [comment] 2018-12-10 23:13
Oh yes, let's finish the wire change first.

**Comment by jba** [comment] 2018-12-10 23:18
But the submodules I was referring to are [samples/appengine](https://github.com/google/go-cloud/blob/master/samples/appengine/go.mod) and [contributebot](https://github.com/google/go-cloud/blob/master/internal/contributebot/go.mod). They both depend on the repo module.

**Comment by zombiezen** [comment] 2018-12-13 23:49
Released in [v0.8.0](https://github.com/google/go-cloud/releases/tag/v0.8.0).

**Closed by zombiezen** 2018-12-13 23:49 UTC
