### ISSUE TITLE
blob: consider Abort or CloseWithError method for blob.Writer

### ISSUE THREAD

**Issue by msample** [google/go-cloud#340] opened 2018-08-16 23:53 UTC
Being able to abort an upload without the object appearing in S3/GCS (or as garbage in RAM from not closing it) can be useful to avoid triggering Cloud/Lambda functions tied to object creation.

Scenario: a long running process with long running multipart uploaders which occasionally run into source data issues (corruption, read timeouts etc) and need to start the uploads from the beginning when the source data issue is resolved.   The current api appears to require closing the Writer and deleting the object which likely creates a race between object deletion and triggering the function.

**Comment by zombiezen** [comment] 2018-08-22 19:48
This is a duplicate of #222.

**Closed by zombiezen** 2018-08-22 19:48 UTC
Labels: duplicate
